name: Deploy to Github Pages
on:
  push:
    branches:
      - main
jobs:
  gh-pages-deploy:
    name: Deploying to Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "15"
      - name: Install packages
        run: npm i
      - name: Test
        run: npm run test
      - name: Set Creds
        run: git config user.name "ov3rk1ll" && git config user.email "overkillerror@gmail.com"
      - name: Deploy
        run: npm run deploy
